[package]
name = "braid_router"
edition = "2024.beta"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
braid_math = { local = "../braid_math" }
braid_cpmm = { local = "../braid_cpmm" }
braid_stable = { local = "../braid_stable" }
braid_clmm = { local = "../braid_clmm" }
braid_clob = { local = "../braid_clob" }

[addresses]
braid_router = "0x0"
